###
GET  http://localhost:8000/getData

###
POST http://localhost:8000/post
Content-Type: application/json

{
    "username":"abc",
    "email":"fhgkehtg@gmail.com",
    "password":"abc@BAC$12",
    "confirmPassword":"abc@ABC$12"
}